GCD0901AppDev/Controllers/TodoesController.cs
using GCD0901AppDev.DTOs.Requests;
using GCD0901AppDev.DTOs.Responses;
using GCD0901AppDev.Models;
using GCD0901AppDev.Repositories.Interfaces;
using GCD0901AppDev.Utils;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GCD0901AppDev.Controllers
{
  [Authorize(Roles = Role.USER)]
  public class TodoesController : Controller
  {
    private readonly UserManager<ApplicationUser> _userManager;
    private ITodoRepository _todoRepos;
    private ICategoryRepository _categoryRepos;
    public TodoesController(
      UserManager<ApplicationUser> userManager,
      ITodoRepository todoRepos,
      ICategoryRepository categoryRepos
      )
    {
      _userManager = userManager;
      _todoRepos = todoRepos;
      _categoryRepos = categoryRepos;
    }
    [HttpGet]
    public IActionResult Index(string category)
    {
      var currentUserId = _userManager.GetUserId(User);
      if (!string.IsNullOrWhiteSpace(category))
      {
        var result = _todoRepos
          .GetAll(currentUserId, category);

        return View(result);
      }

      IEnumerable<Todo> todoes = _todoRepos
        .GetAll(currentUserId);
      return View(todoes);
    }

    [HttpGet]
    public IActionResult Create()
    {
      var viewModel = new CreateTodoRequest()
      {
        Categories = _categoryRepos.GetAll()
      };
      return View(viewModel);
    }
    [HttpPost]
    public async Task<IActionResult> Create(CreateTodoRequest model)
    {
      if (!ModelState.IsValid)
      {
        model = new CreateTodoRequest
        {
          Categories = _categoryRepos.GetAll()
        };
        return View(model);
      }

      var currentUserId = _userManager.GetUserId(User);

      bool isCreated = await _todoRepos.CreateTodo(model, currentUserId);

      if (!isCreated) return BadRequest();
      return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Delete(int id)
    {
      var currentUserId = _userManager.GetUserId(User);
      var isDeleted = _todoRepos.DeleteTodo(id, currentUserId);

      if (!isDeleted) return NotFound();
      return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
      var currentUserId = _userManager.GetUserId(User);
      var todoInDb = _todoRepos.GetTodo(id, currentUserId);
      if (todoInDb is null)
      {
        return NotFound();
      }
      var model = new EditTodoRequest
      {
        Id = todoInDb.Id,
        Description = todoInDb.Description,
        CategoryId = todoInDb.CategoryId,
        Status = todoInDb.Status,
        Categories = _categoryRepos.GetAll()
      };
      return View(model);
    }

    [HttpPost]
    public IActionResult Edit(EditTodoRequest model)
    {
      if (!ModelState.IsValid)
      {
        model = new EditTodoRequest
        {
          Id = model.Id,
          Description = model.Description,
          CategoryId = model.CategoryId,
          Status = model.Status,
          Categories = _categoryRepos.GetAll()
        };
        return View(model);
      }
      var currentUserId = _userManager.GetUserId(User);
      var isEdited = _todoRepos.EditTodo(model, currentUserId);

      if (!isEdited) return BadRequest();
      return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Details(int id)
    {
      var currentUserId = _userManager.GetUserId(User);
      var todoInDb = _todoRepos.GetTodo(id, currentUserId);
      if (todoInDb is null)
      {
        return NotFound();
      }

      var response = new DetailsTodoResponse
      {
        Description = todoInDb.Description,
        CreatedAt = todoInDb.CreatedAt,
        Status = todoInDb.Status,
        CategoryDescription = todoInDb.Category.Description,
        ImageUrl = ConvertByteArrayToStringBase64(todoInDb.ImageData)
      };

      return View(response);
    }

    [HttpGet]
    public IActionResult ByCategory(int id)
    {
      var categoryInDb = _categoryRepos.GetById(id);

      if (categoryInDb == null)
      {
        return NotFound();
      }
      var currentUserId = _userManager.GetUserId(User);
      var todoesByCategoryName = GetTodoesFromCategoryAndUserId(categoryInDb, currentUserId);
      return View("Index", todoesByCategoryName);
    }

    [NonAction]
    private List<Todo> GetTodoesFromCategoryAndUserId(Category category, string userId)
    {
      return category.Todoes
        .Where(t => t.UserId == userId)
        .ToList();
    }

    [NonAction]
    private string ConvertByteArrayToStringBase64(byte[] imageArray)
    {
      string imageBase64Data = Convert.ToBase64String(imageArray);

      return string.Format("data:image/jpg;base64, {0}", imageBase64Data);
    }
  }
}

GCD0901AppDev/Views/Todoes/Create.cshtml
@using GCD0901AppDev.DTOs.Requests
@model CreateTodoRequest

<h1>Create a new Todo</h1>

<form enctype="multipart/form-data" asp-controller="Todoes" asp-action="Create" method="post">
  <div class="form-group">
    <label>Description</label>
    <input asp-for="Description" class="form-control" placeholder="Todo Description ..." />
    <span asp-validation-for="Description" class="text-danger"></span>
  <div class="form-group">
    <label>Category</label>
      <select 
        asp-for="CategoryId" 
        asp-items="@(new SelectList(Model.Categories, "Id", "Description"))" 
        class="form-control">
      </select>
  </div>
  <div class="form-group">
        <dl>
        <dt>
            <label asp-for="@Model.FormFile"></label>
        </dt>
        <dd>
            <input asp-for="@Model.FormFile" type="file">
        </dd>
    </dl>
  </div>

  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Create</button>
  </div>
</form>

GCD0901AppDev/Views/Todoes/Details.cshtml
@using GCD0901AppDev.DTOs.Responses
@model DetailsTodoResponse

<div class="form-group">
  <a asp-controller="Todoes" asp-action="Index" class="btn btn-primary">
    Back to Index
  </a>
</div>

<div class="card" style="width:200px">
  <img src="@Model.ImageUrl"/>
  <div class="card-body">
    <h4 class="card-title">@Model.Description</h4>
    <p class="card-text">Created At: @Model.CreatedAt.ToShortDateString()</p>
    <p class="card-text">Status: @Model.Status.ToString()</p>
    <p class="card-text">Category: @Model.CategoryDescription</p>

  </div>
</div>

GCD0901AppDev/Views/Todoes/Edit.cshtml
@using GCD0901AppDev.DTOs.Requests
@using GCD0901AppDev.Enums
@model EditTodoRequest

<h1>Create a new Todo</h1>

<form asp-controller="Todoes" asp-action="Edit" method="post">
  <input asp-for="@Model.Id" type="hidden" value="@Model.Id" />
  <div class="form-group">
    <label>Description</label>
    <input asp-for="Description" class="form-control" placeholder="Todo Description ..." />
    <span asp-validation-for="Description" class="text-danger"></span>
  </div>
  <div class="form-group">
    <label>Status</label>
    <select asp-for="Status" asp-items="Html.GetEnumSelectList<TodoStatus>()" class="form-control">
    </select>
  </div>
    <div class="form-group">
    <label>Category</label>
      <select 
        asp-for="CategoryId" 
        asp-items="@(new SelectList(Model.Categories, "Id", "Description"))" 
        class="form-control">
      </select>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Edit</button>
  </div>
</form>

GCD0901AppDev/Views/Todoes/Index.cshtml
@model IEnumerable<Todo>

<h1>Index of Todoes</h1>
<div class="form-group">
  <a asp-controller="Todoes" asp-action="Create" class="btn btn-primary">
    Create a new Todo
  </a>
</div>

<div class="form-group">
  <form>
    <input type="text" name="category" placeholder="Search by Category" />
    <button type="submit" class="btn btn-primary">Search</button>
  </form>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Description</th>
      <th scope="col">Created At</th>
      <th scope="col">Status</th>
      <th scope="col">Category</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model){
      <tr>
      <th scope="row">@item.Id</th>
      <td>@item.Description</td>
      <td>@item.CreatedAt.ToShortDateString()</td>
      <td>@item.Status.ToString()</td>
      <td><a 
        asp-action="ByCategory" 
        asp-route-id="@item.CategoryId"
        asp-controller="Todoes">@item.Category.Description</a></td>
      <td>
        <a asp-controller="Todoes" asp-action="Edit" asp-route-id=@item.Id class="btn btn-info"> 
          Edit
        </a>
        <a asp-controller="Todoes" asp-action="Delete" asp-route-id=@item.Id class="btn btn-danger"> 
          Delete
        </a>
        <a asp-controller="Todoes" asp-action="Details" asp-route-id=@item.Id class="btn btn-success"> 
          Details
        </a>
      </td>
    </tr>
  }
   
  </tbody>
</table>